services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quokka-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    # Uncomment the following lines if you need volumes for persistent data
    # volumes:
    #   - ./data:/app/data 