services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quokka-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=./data/games.db
    volumes:
      - db-data:/app/data
    restart: unless-stopped

  # Separate service for seeding the database (run manually when needed)
  seed:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quokka-api-seed
    environment:
      - NODE_ENV=production
      - DATABASE_URL=./data/games.db
    volumes:
      - db-data:/app/data
    command: sh -c "bun run db:seed"
    profiles:
      - seed

volumes:
  db-data: 