export const websiteTypes = [
  { id: 1, type: "official" },
  { id: 2, type: "wikia" },
  { id: 3, type: "wikipedia" },
  { id: 4, type: "facebook" },
  { id: 5, type: "twitter" },
  { id: 6, type: "twitch" },
  { id: 8, type: "instagram" },
  { id: 9, type: "youtube" },
  { id: 10, type: "iphone" },
  { id: 11, type: "ipad" },
  { id: 12, type: "android" },
  { id: 13, type: "steam" },
  { id: 14, type: "reddit" },
  { id: 15, type: "itch" },
  { id: 16, type: "epicgames" },
  { id: 17, type: "gog" },
  { id: 18, type: "discord" },
  { id: 19, type: "bluesky" },
];
